FROM node:16-alpine as builder

WORKDIR /app

COPY . .

RUN yarn install \
  --prefer-offline \
  --frozen-lockfile \
  --non-interactive \
  --production=false

ARG NUXT_ENV_API_HOST
ARG NUXT_ENV_API_HOST_WS
ARG NUXT_ENV_OFFICE_EMAIL
ARG NUXT_ENV_LOGO_BASE64
ARG NUXT_ENV_RAZON_SOCIAL
ARG NUXT_ENV_GIRO
ARG NUXT_ENV_DIRECCION
ARG NUXT_ENV_RUT
ARG NUXT_ENV_FONO
ARG NUXT_ENV_CONTACTO_EMAIL
ARG NUXT_ENV_CEO_SIGNATURE
ARG NUXT_ENV_CEO_NAME
ARG NUXT_ENV_CEO_PROFESION

ENV NUXT_ENV_API_HOST=$NUXT_ENV_API_HOST
ENV NUXT_ENV_API_HOST_WS=$NUXT_ENV_API_HOST_WS
ENV NUXT_ENV_OFFICE_EMAIL=$NUXT_ENV_OFFICE_EMAIL
ENV NUXT_ENV_LOGO_BASE64=$NUXT_ENV_LOGO_BASE64
ENV NUXT_ENV_RAZON_SOCIAL=$NUXT_ENV_RAZON_SOCIAL
ENV NUXT_ENV_GIRO=$NUXT_ENV_GIRO
ENV NUXT_ENV_DIRECCION=$NUXT_ENV_DIRECCION
ENV NUXT_ENV_RUT=$NUXT_ENV_RUT
ENV NUXT_ENV_FONO=$NUXT_ENV_FONO
ENV NUXT_ENV_CONTACTO_EMAIL=$NUXT_ENV_CONTACTO_EMAIL
ENV NUXT_ENV_CEO_SIGNATURE=$NUXT_ENV_CEO_SIGNATURE
ENV NUXT_ENV_CEO_NAME=$NUXT_ENV_CEO_NAME
ENV NUXT_ENV_CEO_PROFESION=$NUXT_ENV_CEO_PROFESION

RUN yarn build

RUN rm -rf node_modules && \
  NODE_ENV=production yarn install \
  --prefer-offline \
  --pure-lockfile \
  --non-interactive \
  --production=true

FROM node:lts

WORKDIR /app

COPY --from=builder /app  .

ENV HOST 0.0.0.0
EXPOSE 80

CMD [ "yarn", "start" ]
